version: '3.4'

services:
  webserver:
    container_name: httpd
    build: ./httpd
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpdocs/html:/var/www/html
    links:
      - php
    networks:
      - app-network

  php:
    container_name: php
    image: php:7.4.6-fpm-alpine3.11
    restart: unless-stopped
    #ports:
    #  - "9000:9000"
    volumes:
      - ./httpdocs:/var/www
    networks:
      - app-network

  db:
    image: mysql:8.0.19
    container_name: db
    hostname: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    restart: unless-stopped
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    networks:
      - app-network

volumes:

  dbdata:

networks:
  app-network:
    driver: bridge